// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByj2uBF0sUiVcavVR6Ns62S3X9Fs-NUhY',
    appId: '1:179301090390:web:6758443a26f8398aac67f7',
    messagingSenderId: '179301090390',
    projectId: 'flutter-template-782aa',
    authDomain: 'flutter-template-782aa.firebaseapp.com',
    storageBucket: 'flutter-template-782aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStOIfyH8YRnHV8S3fgy-4H1fdSTU7WN0',
    appId: '1:179301090390:android:5f9df247b0bd50ceac67f7',
    messagingSenderId: '179301090390',
    projectId: 'flutter-template-782aa',
    storageBucket: 'flutter-template-782aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18krrLE809pcOuvRKabzkjFOac2MHXn4',
    appId: '1:179301090390:ios:e41dc36b648630d4ac67f7',
    messagingSenderId: '179301090390',
    projectId: 'flutter-template-782aa',
    storageBucket: 'flutter-template-782aa.appspot.com',
    iosClientId: '179301090390-h396gjidppbjjnni7a7kf799d5t8353r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC18krrLE809pcOuvRKabzkjFOac2MHXn4',
    appId: '1:179301090390:ios:e41dc36b648630d4ac67f7',
    messagingSenderId: '179301090390',
    projectId: 'flutter-template-782aa',
    storageBucket: 'flutter-template-782aa.appspot.com',
    iosClientId: '179301090390-h396gjidppbjjnni7a7kf799d5t8353r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
